############################
##### Overall workflow #####
############################

# Type of input data (currently only supports 'Single')
DATA: ""

# File path to the reference genome (.fasta)
REFGENOME: ""

# Temporary file directory
TEMPDIR: ""

# Whole exome sequence settings (leave blank if analysing other data such as whole genome sequence data)
WES:
  # File path to the exome capture regions over which to operate (prefix with the '-L' flag)
  INTERVALS: ""
  # Padding (in bp) to add to each region (prefix with the '-ip' flag)
  PADDING: ""

##############################
##### Base recalibration #####
##############################

# Resources to used for base recalibration (prefix each resource with the '--knownSites' flag)
RECALIBRATION:
  RESOURCES: "--knownSites /NGS/scratch/KSCBIOM/HumanGenomics/publicData/human_refs/GATK/b37/dbsnp_138.b37.vcf
            --knownSites /NGS/scratch/KSCBIOM/HumanGenomics/publicData/human_refs/GATK/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
            --knownSites /NGS/scratch/KSCBIOM/HumanGenomics/publicData/human_refs/GATK/b37/1000G_phase1.indels.b37.vcf"
