############################
##### Overall workflow #####
############################

# Type of input data (either 'Single' or 'Cohort')
DATA: ""

# File path to reference genome
REFGENOME: ""

# Temporary file directory
TEMPDIR: ""

# WES settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: ""
  # Padding (in bp) to add to each interval
  PADDING: ""

############################
######### Trimming #########
############################

# Adapter sequence to be trimmed (eg. `--illumina`, `--nextera` or `--small_rna`)
TRIMMING:
  ADAPTERS: ""

##############################
##### Base recalibration #####
##############################

# Resources used for base recalibration
RECALIBRATION:
  RESOURCES: ""